Controllers/EquipmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using BarangaySystem.Data;
using BarangaySystem.Models;
using BarangaySystem.Models.APIServices;
using BarangaySystem.Models.ItemModels;
using BarangaySystem.Models.ModelModels;
using BarangaySystem.Utilities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using BarangaySystem.Models.IdentityModels;

namespace BarangaySystem.Controllers
{
    [Authorize]
    public class EquipmentController : Controller
    {
        public readonly UserManager<ApplicationUser> _userManager;

        public EquipmentController(UserManager<ApplicationUser> userManager){

            _userManager = userManager;
        }
        
        private string LoggedUser{
            get{
                return _userManager.Users.FirstOrDefault(x => x.UserName == User.Identity.Name).Fullname;
            }
        }


        [Authorize]
        public IActionResult ViewEquipment()
        {
            return View();
        }
        public IActionResult Inventory()
        {
            return View();
        }


        [HttpGet("[controller]/NewItemModel/{key}")]
        public IActionResult NewItemModel(string key)
        {
            if (!key.IsValidKey())
            {
                return NotFound();
            }
            string id = key.DecryptString();
            var api = new APIModels();
            var itemModel = new ModelModel();
            itemModel.ItemId = int.Parse(id);
            itemModel.Key = key;
            itemModel.BrandName = api.GetBrandNameById(int.Parse(id));
            return View(itemModel);
        }

        

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult SaveNewModel(ModelModel modelModel)
        {
            if (!ModelState.IsValid)
            {
                foreach (var err in ModelState.Values)
                {
                    foreach (var error in err.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.ErrorMessage);
                    }
                }
                return View("NewItemModel", modelModel);
            }
            var api = new APIModels();
            string message = string.Empty;
            bool flag = api.Add(model: modelModel, LoggedUser: LoggedUser, message: out message);
            if(!flag)
            {
                ModelState.AddModelError(string.Empty, message);
                return View("NewItemModel", modelModel);
            }
            message = "Successfully Added";
            TempData["Success"] = message;
            return RedirectToAction(nameof(EquipmentController.ViewEquipment));
            // return Json(new{
            //     ItemId = modelModel.ItemId,
            //     Name = modelModel.Name,
            //     Price = modelModel.Price,
            //     AddedBy = LoggedUser,
            //     DateAdded = DateTime.Now
            // });
        }



        [HttpGet("[controller]/EditItemModel/{key}")]
        public IActionResult EditItemModel(string Key)
        {
            if (!Key.IsValidKey())
            {
                return NotFound();
            }
            var api = new APIModels();
            string id = Key.DecryptString();
            return View(api.GetModel(int.Parse(id)));
        }

        [HttpPost]
        public IActionResult UpdateItemModel(ModelModel modelModel)
        {
            if (!ModelState.IsValid)
            {
                foreach (var err in ModelState.Values)
                {
                    foreach (var error in err.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.ErrorMessage);
                    }
                }
                return View("EditItemModel", modelModel);
            }

            if(!modelModel.Id.ToString().Validate(modelModel.Key))
            {
                return View("EditItemModel", modelModel);
            }

            var api = new APIModels();
            string message = string.Empty;
            bool flag = api.Update(modelModel: modelModel, addedBy: LoggedUser, message: out message);
            if(!flag)
            {
                ModelState.AddModelError(string.Empty, message);
                TempData["Error"] = message;
                return View("EditItemModel", modelModel);
            }
            TempData["Success"] = message;
            return RedirectToAction(nameof(EquipmentController.ViewEquipment));
            // return Json(new{
            //     Id = itemModel.Id,
            //     Key = itemModel.Key,
            //     Type = itemModel.TypeOfItem,
            //     Name = itemModel.Name,
            //     Brand = itemModel.Brand
            // });
        }

        [HttpPost]
        public JsonResult GetEquipmentData(){

            string search = Request.Form["search[value]"];
            int start = int.Parse(Request.Form["start"]),
                pageSize = int.Parse(Request.Form["length"]),
                count = 0;
            var db = new DbBarangayContext();
            var query = db.Models;
            count = query.Count();
            var rows = query.OrderByDescending(x => x.Id).Skip(start).Take(pageSize);

            var api = new APIModels();
            var result = !search.IsEmpty() ? api.SearchEquipmentData(search,start,pageSize, out count) : 
                                             api.GetEquipmentData(start,pageSize, out count);
            return Json(new{
                data = result,
                draw = Request.Form["draw"],
                recordsTotal = count,
                recordsFiltered = count,
            });
        }
        
        [HttpPost]
        public JsonResult GetInventory(){

            string search = Request.Form["search[value]"];
            int start = int.Parse(Request.Form["start"]),
                pageSize = int.Parse(Request.Form["length"]),
                count = 0;
            var db = new DbBarangayContext();
            var query = db.Models;
            count = query.Count();
            var rows = query.OrderByDescending(x => x.Id).Skip(start).Take(pageSize);

            var api = new APIModels();
            var result = api.GetInventoryData(start,pageSize, out count);
            return Json(new{
                data = result,
                draw = Request.Form["draw"],
                recordsTotal = count,
                recordsFiltered = count,
            });
        }

        [HttpGet]
        public JsonResult Remove(string key)
        {
            
            var api = new APIModels();
            string message = string.Empty;
            var flag = api.Delete(key.DecryptString().ValidateNumber(), addedBy: LoggedUser, message: out message);

            return Json(new{
                status = flag,
                message = message
            });
        }
    }
}

Controllers/ItemController.cs
using System.Collections.Generic;
using System.Linq;
using BarangaySystem.Data;
using BarangaySystem.Models.APIServices;
using BarangaySystem.Models.IdentityModels;
using BarangaySystem.Models.ItemModels;
using BarangaySystem.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BarangaySystem.Controllers
{
    [Authorize]
    public class ItemController : Controller
    {
        
        public readonly UserManager<ApplicationUser> _userManager;

        public ItemController(UserManager<ApplicationUser> userManager){

            _userManager = userManager;
        }
        
        private string LoggedUser{
            get{
                return _userManager.Users.FirstOrDefault(x => x.UserName == User.Identity.Name).Fullname;
            }
        }
        public IActionResult ViewItem() => View();
        public IActionResult NewItem() => View();

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult SaveNewItem(ItemModel itemModel)
        {
            string message = string.Empty;
            if (!ModelState.IsValid)
            {
                foreach (var err in ModelState.Values)
                {
                    foreach (var error in err.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.ErrorMessage);
                    }
                }
                return RedirectToAction(nameof(ItemController.NewItem), itemModel);
            }
            var api = new APIItems();
            bool flag = api.Add(model: itemModel, addedBy: LoggedUser, message: out message);
            if(!flag)
            {
                ModelState.AddModelError(string.Empty, message);
                return View("NewItem", itemModel);
            }
            message = "Successfully Added";
            TempData["Success"] = message;
            return RedirectToAction(nameof(ItemController.NewItem));
            // return Json(new{
            //     TypeOfItem = itemModel.TypeOfItem,
            //         Name = itemModel.Name,
            //         Brand = itemModel.Brand,
            //         AddedBy = LoggedUser
            // });
        }

        [HttpGet("[controller]/EditItem/{Key}")]
        public IActionResult EditItem(string Key)
        {
            if (!Key.IsValidKey())
            {
                return NotFound();
            }
            var api = new APIItems();
            string id = Key.DecryptString();
            return View(api.GetItem(int.Parse(id)));
        }

        [HttpPost]
        public IActionResult UpdateItem(ItemModel itemModel)
        {
            string message = string.Empty;
            if (!ModelState.IsValid)
            {
                foreach (var err in ModelState.Values)
                {
                    foreach (var error in err.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.ErrorMessage);
                    }
                }
                return View("EditItem",itemModel);
            }

            if(!itemModel.Id.ToString().Validate(itemModel.Key))
            {
                
                return View("EditItem",itemModel);
            }

            var api = new APIItems();
            bool flag = api.Update(itemModel: itemModel, addedBy: LoggedUser, message: out message);
            if(!flag)
            {
                ModelState.AddModelError(string.Empty, message);
                TempData["Error"] = message;
                return View("EditItem",itemModel);
            }
            TempData["Success"] = message;
            return RedirectToAction(nameof(ItemController.ViewItem));
            // return Json(new{
            //     Id = itemModel.Id,
            //     Key = itemModel.Key,
            //     Type = itemModel.TypeOfItem,
            //     Name = itemModel.Name,
            //     Brand = itemModel.Brand
            // });
        }

        [HttpPost]
        public JsonResult GetItemsData(){

            string search = Request.Form["search[value]"];
            int start = int.Parse(Request.Form["start"]),
                pageSize = int.Parse(Request.Form["length"]),
                count = 0;
            var db = new DbBarangayContext();
            var query = db.Items;
            count = query.Count();
            var rows = query.OrderByDescending(x => x.Id).Skip(start).Take(pageSize);

            var api = new APIItems();
            var result = !search.IsEmpty() ? api.SearchItemsData(search,start,pageSize, out count) : 
                                             api.GetItemData(start,pageSize, out count);
            return Json(new{
                data = result,
                draw = Request.Form["draw"],
                recordsTotal = count,
                recordsFiltered = count,
            });

            // var items = new List<object> ();
            // foreach (var em in rows) {
            //     items.Add (new {
            //         Id = em.Id,
            //         TypeOfItem = em.TypeofItem,
            //         Name = em.Name,
            //         Brand = em.Brand,
            //         Models = db.Models.Where(x => x.ItemId == em.Id).Count().ToString()
            //     });
                
            // }
            // return Json(new{
            //     data = items,
            //     draw = Request.Form["draw"],
            //     recordsTotal = count,
            //     recordsFiltered = count,
            //     });
        }

        [HttpGet]
        public JsonResult Remove(string key)
        {
            
            var api = new APIItems();
            string message = string.Empty;
            var flag = api.Delete(key.DecryptString().ValidateNumber(), out message);

            return Json(new{
                status = flag,
                message = message
            });
        }
        
    }
}

Views/Equipment/EditItemModel.cshtml
@using BarangaySystem.Models.APIServices
@model BarangaySystem.Models.ModelModels.ModelModel
@{
    Layout = "~/Views/Shared/_Equipment.cshtml";
}
<section>
    <div class="row">
        <div class="col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Edit for <b><u>@Model.BrandName</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <!--content here...-->
                        @if(TempData["Success"] != null){
                            <div class="row"><div class="alert with-close alert-success alert-dismissible fade show Alert">@TempData["Success!"]
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">×</span>
                                    </button>
                            </div></div>
                        }
                    <div asp-validation-summary="ModelOnly" class="alert alert-danger"></div>
                    <form asp-action="UpdateItemModel" asp-controller="Equipment" method="post">
                        <input asp-for="Id" type="hidden">
                        <input asp-for="Key" type="hidden">
                        <input asp-for="ItemId" type="hidden">
                        <div class="row">
                            <div class="col-md-6">
                                <label asp-for="Name" class="label-control">Name<b> *</b></label>
                                <input asp-for="Name" class="form-control" placeholder="Enter Name" autofocus>
                                <span asp-validation-for="Name" class="text-danger"></span>
                                </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6"
                            <label>Quantity<b> *</b></label>
                            <input asp-for="Quantity" class="form-control" type="text" placeholder="Enter Quantity">
                            <span asp-validation-for="Quantity" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                            <label asp-for="Price">Price<b> *</b></label>
                            <input asp-for="Price" class="form-control amounts" placeholder="Enter Price">
                            <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="row" style="margin: 10px 0 0 10px;">
                            <button type="submit" class="btn btn-primary">Submit</button>
                            <button type="button" class="btn btn-danger" style="margin-left:10px;"><a asp-action="ViewEquipment" asp-controller="Equipment" style="color:white;">Cancel</a></button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</section>

Views/Equipment/Inventory.cshtml
@{
    Layout = "~/Views/Shared/_Inventory.cshtml";
}
<section>
    <div class="row">
        <div class="col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2><i class="fa fa-file-text"></i> Inventory Report</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="table-responsive">
                        <table id="tblInventory" class="table datatable table-bordered">
                            <thead>
                                <tr>
                                    <th>Item Name</th>
                                    <th>Price</th>
                                    <th>Available Items</th>
                                    <th>Total Price</th>
                                    <th>Borrowed Quantity</th>
                                </tr>
                            </thead> 
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Views/Equipment/NewItemModel.cshtml
@using BarangaySystem.Models.APIServices
@model BarangaySystem.Models.ModelModels.ModelModel
@{
    Layout = "~/Views/Shared/_Equipment.cshtml";
}
<section>
    <div class="row">
        <div class="col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Add Model for <b><u>@Model.BrandName</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <!--content here...-->
                        @if(TempData["Success"] != null){
                            <div class="row"><div class="alert alert-success">@TempData["Success!"]
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">×</span>
                                    </button>
                            </div></div>
                        }
                    <div asp-validation-summary="ModelOnly" class="alert alert-danger"></div>
                    <form asp-action="SaveNewModel" asp-controller="Equipment" method="post">
                        <input asp-for="Id" type="hidden">
                        <input asp-for="Key" type="hidden">
                        <input asp-for="ItemId" type="hidden">
                        <div class="row">
                            <div class="col-md-6">
                                <label asp-for="Name" class="label-control">Name<b> *</b></label>
                                <input asp-for="Name" class="form-control" placeholder="Enter Name" autofocus>
                                <span asp-validation-for="Name" class="text-danger"></span>
                                </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6"
                            <label>Quantity<b> *</b></label>
                            <input asp-for="Quantity" class="form-control" type="number" value="" placeholder="Enter Quantity">
                            <span asp-validation-for="Quantity" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                            <label asp-for="Price">Price<b> *</b></label>
                            <input asp-for="Price" class="form-control amounts" placeholder="Enter Price">
                            <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="row" style="margin: 10px 0 0 10px;">
                            <button type="submit" class="btn btn-primary">Submit</button>
                            <button type="button" class="btn btn-danger" style="margin-left:10px;"><a asp-action="ViewItem" asp-controller="Item" style="color:white;">Cancel</a></button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</section>

Views/Equipment/ViewEquipment.cshtml
@{
    Layout = "~/Views/Shared/_ViewEquipment.cshtml";
}
<section>
    <div class="row">
        <div class="col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Equipment Models</h2><button type="button" class="btn btn-success btn-sm" style="float:right;"><a asp-action="Inventory" asp-controller="Equipment" style="color:white;">Inventory Report</a></button>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <!--content here...-->     
                    <table id="tblEquipment" class="table datatable table-bordered">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Brand</th>
                                <th>Model</th>
                                <th>Price</th>
                                <th>Quantity</th>
                                <th>Total Price</th>
                                <th>Status</th>
                                <th>Added By</th>
                                <th>Date Added</th>
                                <th>Date Modified</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</section>