Controllers/ItemController.cs
using System.Collections.Generic;
using System.Linq;
using BarangaySystem.Data;
using BarangaySystem.Models.APIServices;
using BarangaySystem.Models.IdentityModels;
using BarangaySystem.Models.ItemModels;
using BarangaySystem.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BarangaySystem.Controllers
{
    [Authorize]
    public class ItemController : Controller
    {
        
        public readonly UserManager<ApplicationUser> _userManager;

        public ItemController(UserManager<ApplicationUser> userManager){

            _userManager = userManager;
        }
        
        private string LoggedUser{
            get{
                return _userManager.Users.FirstOrDefault(x => x.UserName == User.Identity.Name).Fullname;
            }
        }
        public IActionResult ViewItem() => View();
        public IActionResult NewItem() => View();

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult SaveNewItem(ItemModel itemModel)
        {
            string message = string.Empty;
            if (!ModelState.IsValid)
            {
                foreach (var err in ModelState.Values)
                {
                    foreach (var error in err.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.ErrorMessage);
                    }
                }
                return RedirectToAction(nameof(ItemController.NewItem), itemModel);
            }
            var api = new APIItems();
            bool flag = api.Add(model: itemModel, addedBy: LoggedUser, message: out message);
            if(!flag)
            {
                ModelState.AddModelError(string.Empty, message);
                return View("NewItem", itemModel);
            }
            message = "Successfully Added";
            TempData["Success"] = message;
            return RedirectToAction(nameof(ItemController.NewItem));
            // return Json(new{
            //     TypeOfItem = itemModel.TypeOfItem,
            //         Name = itemModel.Name,
            //         Brand = itemModel.Brand,
            //         AddedBy = LoggedUser
            // });
        }

        [HttpGet("[controller]/EditItem/{Key}")]
        public IActionResult EditItem(string Key)
        {
            if (!Key.IsValidKey())
            {
                return NotFound();
            }
            var api = new APIItems();
            string id = Key.DecryptString();
            return View(api.GetItem(int.Parse(id)));
        }

        [HttpPost]
        public IActionResult UpdateItem(ItemModel itemModel)
        {
            string message = string.Empty;
            if (!ModelState.IsValid)
            {
                foreach (var err in ModelState.Values)
                {
                    foreach (var error in err.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.ErrorMessage);
                    }
                }
                return View("EditItem",itemModel);
            }

            if(!itemModel.Id.ToString().Validate(itemModel.Key))
            {
                
                return View("EditItem",itemModel);
            }

            var api = new APIItems();
            bool flag = api.Update(itemModel: itemModel, addedBy: LoggedUser, message: out message);
            if(!flag)
            {
                ModelState.AddModelError(string.Empty, message);
                TempData["Error"] = message;
                return View("EditItem",itemModel);
            }
            TempData["Success"] = message;
            return RedirectToAction(nameof(ItemController.ViewItem));
            // return Json(new{
            //     Id = itemModel.Id,
            //     Key = itemModel.Key,
            //     Type = itemModel.TypeOfItem,
            //     Name = itemModel.Name,
            //     Brand = itemModel.Brand
            // });
        }

        [HttpPost]
        public JsonResult GetItemsData(){

            string search = Request.Form["search[value]"];
            int start = int.Parse(Request.Form["start"]),
                pageSize = int.Parse(Request.Form["length"]),
                count = 0;
            var db = new DbBarangayContext();
            var query = db.Items;
            count = query.Count();
            var rows = query.OrderByDescending(x => x.Id).Skip(start).Take(pageSize);

            var api = new APIItems();
            var result = !search.IsEmpty() ? api.SearchItemsData(search,start,pageSize, out count) : 
                                             api.GetItemData(start,pageSize, out count);
            return Json(new{
                data = result,
                draw = Request.Form["draw"],
                recordsTotal = count,
                recordsFiltered = count,
            });

            // var items = new List<object> ();
            // foreach (var em in rows) {
            //     items.Add (new {
            //         Id = em.Id,
            //         TypeOfItem = em.TypeofItem,
            //         Name = em.Name,
            //         Brand = em.Brand,
            //         Models = db.Models.Where(x => x.ItemId == em.Id).Count().ToString()
            //     });
                
            // }
            // return Json(new{
            //     data = items,
            //     draw = Request.Form["draw"],
            //     recordsTotal = count,
            //     recordsFiltered = count,
            //     });
        }

        [HttpGet]
        public JsonResult Remove(string key)
        {
            
            var api = new APIItems();
            string message = string.Empty;
            var flag = api.Delete(key.DecryptString().ValidateNumber(), out message);

            return Json(new{
                status = flag,
                message = message
            });
        }
        
    }
}

Controllers/PermitController.cs
using System;
using System.Linq;
using BarangaySystem.Data;
using BarangaySystem.Models.APIServices;
using BarangaySystem.Models.IdentityModels;
using BarangaySystem.Models.PermitModels;
using BarangaySystem.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BarangaySystem.Controllers
{
    [Authorize]
    public class PermitController : Controller
    {
        public readonly UserManager<ApplicationUser> _userManager;

        public PermitController(UserManager<ApplicationUser> userManager){

            _userManager = userManager;
        }
        
        private string LoggedUser{
            get{
                return _userManager.Users.FirstOrDefault(x => x.UserName == User.Identity.Name).Fullname;
            }
        }
        public IActionResult ViewBarangay()
        {
            return View();
        }
        public IActionResult NewBarangay() => View();

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult SaveNewBarangay(BarangayModel barangayModel)
        {
            string message = string.Empty;
            if (!ModelState.IsValid)
            {
                foreach (var err in ModelState.Values)
                {
                    foreach (var error in err.Errors)
                    {
                        message = "Something wen't wrong";
                        TempData["Error"] = message;
                        ModelState.AddModelError(string.Empty, error.ErrorMessage);
                    }
                }
                return RedirectToAction(nameof(PermitController.NewBarangay), barangayModel);
            }
            var api = new APIBarangay();
            bool flag = api.Add(barangayModel: barangayModel, ReleasedBy: LoggedUser, message: out message);
            if(!flag)
            {
                ModelState.AddModelError(string.Empty, message);
                return View("NewBarangay", barangayModel);
            }
            message = "Barangay Permit Record has been Successfully Added";
            TempData["Success"] = message;
            return RedirectToAction(nameof(PermitController.NewBarangay));
        }

        [HttpPost]
        public JsonResult GetBarangayData(){

            string search = Request.Form["search[value]"];
            int start = int.Parse(Request.Form["start"]),
                pageSize = int.Parse(Request.Form["length"]),
                count = 0;
            var db = new DbBarangayContext();
            var query = db.Blotter;
            count = query.Count();
            var rows = query.OrderByDescending(x => x.Id).Skip(start).Take(pageSize);

            var api = new APIBarangay();
            var result = !search.IsEmpty() ? api.SearchBarangayData(search,start,pageSize, out count) : 
                                             api.GetBarangayDatas(start,pageSize, out count);
            return Json(new{
                data = result,
                draw = Request.Form["draw"],
                recordsTotal = count,
                recordsFiltered = count,
            });
        }

        public PartialViewResult GetAddress(long id)
        {
            var api = new APIBarangay();
            return PartialView("Partials/Controls/Address", api.GetAddressValues(id));
        }
    }
}

Controllers/PersonController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BarangaySystem.Data;
using BarangaySystem.Models.APIServices;
using BarangaySystem.Models.IdentityModels;
using BarangaySystem.Models.PersonModels;
using BarangaySystem.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BarangaySystem.Controllers
{
    [Authorize]
    public class PersonController : Controller
    {
        public readonly UserManager<ApplicationUser> _userManager;

        public PersonController(UserManager<ApplicationUser> userManager){

            _userManager = userManager;
        }
        
        private string LoggedUser{
            get{
                return _userManager.Users.FirstOrDefault(x => x.UserName == User.Identity.Name).Fullname;
            }
        }
        public IActionResult ViewPerson() => View();
        public IActionResult NewPerson() => View();

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult SaveNewPerson(PersonModel personModel)
        {
            string message = string.Empty;
            if (!ModelState.IsValid)
            {
                foreach (var err in ModelState.Values)
                {
                    foreach (var error in err.Errors)
                    {
                        message = "Oppss.!! Error!";
                        TempData["Error"] = message;
                        ModelState.AddModelError(string.Empty, error.ErrorMessage);
                    }
                }
                return RedirectToAction(nameof(PersonController.NewPerson), personModel);
            }
            var api = new APIPersons();
            bool flag = api.Add(personModel: personModel, addedBy: LoggedUser, message: out message);
            if(!flag)
            {
                ModelState.AddModelError(string.Empty, message);
                return View("NewPerson", personModel);
            }
            message = "Person Data has been Successfully Added";
            TempData["Success"] = message;
            return RedirectToAction(nameof(PersonController.NewPerson));
        }

        [HttpGet("[controller]/EditPerson/{key}")]
        public IActionResult EditPerson(string key)
        {
            if (!key.IsValidKey())
            {
                return NotFound();
            }
            var api = new APIPersons();
            string id = key.DecryptString();
            return View(api.GetPerson(int.Parse(id)));
        }

        public IActionResult ViewBorrowed()
        {
            return View();
        }

        public PartialViewResult GetModels(long id)
        {
            var api = new APIPersons();
            return PartialView("Partials/Controls/Models", api.GetModelValues(id));
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult UpdatePerson(PersonModel personModel)
        {
            if (!ModelState.IsValid)
            {
                foreach (var err in ModelState.Values)
                {
                    foreach (var error in err.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.ErrorMessage);
                    }
                }
                return NotFound();
            }

            if(!personModel.Id.ToString().Validate(personModel.Key))
            {
                return NotFound();
            }

            var api = new APIPersons();
            string message = string.Empty;
            bool flag = api.Update(personModel: personModel, addedBy: LoggedUser, message: out message);
            if(!flag)
            {
                ModelState.AddModelError(string.Empty, message);
                TempData["Error"] = message;
                return RedirectToAction(nameof(PersonController.EditPerson),personModel);
            }
            TempData["Success"] = message;
            return RedirectToAction(nameof(PersonController.ViewPerson));
        }


        [HttpPost]
        public JsonResult GetPersonsData(){

            string search = Request.Form["search[value]"];
            int start = int.Parse(Request.Form["start"]),
                pageSize = int.Parse(Request.Form["length"]),
                count = 0;
            var db = new DbBarangayContext();
            var query = db.Persons;
            count = query.Count();
            var rows = query.OrderByDescending(x => x.Id).Skip(start).Take(pageSize);

            var api = new APIPersons();
            var result = !search.IsEmpty() ? api.SearchPersonsData(search,start,pageSize, out count) : 
                                             api.GetPersonsData(start,pageSize, out count);
            return Json(new{
                data = result,
                draw = Request.Form["draw"],
                recordsTotal = count,
                recordsFiltered = count,
            });
        }

        [HttpPost]
        public JsonResult GetBorrowData(string key){

            string search = Request.Form["search[value]"];
            int start = int.Parse(Request.Form["start"]),
                pageSize = int.Parse(Request.Form["length"]),
                count = 0;
            var db = new DbBarangayContext();
            var query = db.BorrowItem;
            count = query.Count();
            var rows = query.OrderByDescending(x => x.Id).Skip(start).Take(pageSize);

            string id = key.DecryptString();

            var api = new APIBorrowItem();
            var result = !search.IsEmpty() ? api.SearchBorrowsData(search,start,pageSize, out count) : 
                                             api.GetBorrowsData(start,pageSize, out count);
            return Json(new{
                data = result,
                draw = Request.Form["draw"],
                recordsTotal = count,
                recordsFiltered = count,
            });
            
        }


        [HttpGet]
        public JsonResult Remove(string key)
        {
            
            var api = new APIPersons();
            string message = string.Empty;
            var flag = api.Delete(key.DecryptString().ValidateNumber(), addedBy: LoggedUser, message: out message);

            return Json(new{
                status = flag,
                message = message
            });
        }
    }
}

Views/Shared/Partials/Menus/_LeftSideNavigation.cshtml
<div class="col-md-3 left_col left_col menu_fixed">
    <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
            <a asp-action="index" asp-controller="Home" class="site_title"><img src="~/images/default/logo/BARANGAY1.png" style="width:30px; height:30px;"> <span>BRGY SAMBAG 1</span></a>
        </div>

        <div class="clearfix"></div>

            <!-- menu profile quick info -->
          <!-- <div class="profile clearfix">
            <div class="profile_pic">
              <img src="~/images/default/users/admin.jpg" alt="..." class="img-circle profile_img">
            </div>
              <div class="profile_info">
                <span>Welcome,</span>
                <h2>Renzo Chorizo</h2>
              </div>
          </div> -->
            <!-- /menu profile quick info -->

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">

                  <li><a><i class="fa fa-laptop"></i> Equipments <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                          <li><a asp-action="NewItem" asp-controller="Item">Add</a></li>
                          <li><a asp-action="ViewItem" asp-controller="Item">View</a></li>
                          <li><a asp-action="ViewEquipment" asp-controller="Equipment">View Models</a></li>
                      </li>
                    </ul>
                  </li>

                  <li><a><i class="fa fa-hospital-o"></i> Facilities <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                          <li><a asp-action="NewFacility" asp-controller="Facility">Add</a></li>
                          <li><a asp-action="ViewFacility" asp-controller="Facility">View</a></li>
                      </li>
                    </ul>
                  </li>

                  <li><a><i class="fa fa-folder-open-o"></i> Permits & Clearances <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="#">Barangay <span class="fa fa-chevron-down"></span></a> 
                        <ul class="nav child_menu">
                          <li><a asp-action="NewBarangay" asp-controller="Permit">Add</a></li>
                          <li><a asp-action="ViewBarangay" asp-controller="Permit">View</a></li>
                        </ul> 
                      </li>

                      <li><a href="#">Business <span class="fa fa-chevron-down"></span></a> 
                        <ul class="nav child_menu">
                          <li><a asp-action="NewBusiness" asp-controller="Business">Add</a></li>
                          <li><a asp-action="ViewBusiness" asp-controller="Business">View</a></li>
                        </ul> 
                      </li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-user"></i>Borrowers Information <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                          <li><a asp-action="NewBorrow" asp-controller="BorrowItem">Add</a></li>
                          <li><a asp-action="ViewBorrowed" asp-controller="Person">View</a></li>
                    </ul>
                  </li>

                  <li><a><i class="fa fa-legal"></i>Blotter <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                          <li><a asp-action="NewBlotter" asp-controller="Blotter">Add</a></li>
                          <li><a asp-action="ViewBlotter" asp-controller="Blotter">View</a></li>
                    </ul>
                  </li>

                  <li><a><i class="fa fa-user"></i>Residence Information <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                          <li><a asp-action="NewPerson" asp-controller="Person">Add</a></li>
                          <li><a asp-action="ViewPerson" asp-controller="Person">View</a></li>
                    </ul>
                  </li>

                  @if(User.IsInRole("Administrator"))
                  {
                  <li><a><i class="fa fa-gear"></i> Account <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                          <li><a asp-action="NewUser" asp-controller="Account">Add</a></li>
                          <li><a asp-action="ViewAccount" asp-controller="Account">View</a></li>
                    </ul>
                  </li>
                  }
                </ul>
              </div>
            </div>
            <!-- /sidebar menu -->

            <!-- /menu footer buttons -->
            <div class="sidebar-footer hidden-small">
              <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
              </a>
              <form id="formLogout" asp-action="Logout" asp-controller="Account">
                <a data-toggle="tooltip" data-placement="top" title="Logout" onclick="javascript:getElementById('frmLogout').submit()">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
              </a> 
              </form>
            </div>
            <!-- /menu footer buttons -->
    </div>  
</div>

Views/Shared/Partials/Menus/_TopBarNavigation.cshtml
@using Microsoft.AspNetCore.Identity 
@using Microsoft.AspNetCore.Identity.EntityFrameworkCore
@using BarangaySystem.Models.IdentityModels
@inject UserManager<ApplicationUser> UserManager
@{
    var currentUser = UserManager.Users.FirstOrDefault(x => x.UserName == User.Identity.Name);
    string usersPath = "/images/default/users/",
            userImage = string.Empty;
    var imagePath ="admin.jpg";
    
    userImage = string.Concat(usersPath,imagePath);
}
<!-- Top Navigation -->
      <div class="top_nav">
        <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-right">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <img src="~/images/default/logo/BARANGAY1.png" style="width:30px; height:30px;" alt="BRGY">
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <li><a asp-action="Index" asp-controller="Account"> Profile</a></li>
                      <li>
                        <form id="frmLogout" class="form-group" asp-action="Logout" asp-controller="Account">
                          <a onclick="javascript:getElementById('frmLogout').submit()">
                            <i class="fa fa-sign-out pull-right"></i> Log Out
                          </a>
                        </form>
                      </li>
                  </ul>
                </li>

              </ul>
            </nav>
        </div>
      </div>