Controllers/BusinessController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using BarangaySystem.Models.APIServices;
using BarangaySystem.Models.IdentityModels;
using BarangaySystem.Models.PermitModels;
using BarangaySystem.Utilities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BarangaySystem.Controllers
{
    public class BusinessController : Controller
    {
        public readonly UserManager<ApplicationUser> _userManager;

        public BusinessController(UserManager<ApplicationUser> userManager){

            _userManager = userManager;
        }
        
        private string LoggedUser{
            get{
                return _userManager.Users.FirstOrDefault(x => x.UserName == User.Identity.Name).Fullname;
            }
        }
        public IActionResult NewBusiness() => View();

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> NewBusiness(BusinessModel businessModel)
        {
            var xb = new System.Text.StringBuilder();
            if(!ModelState.IsValid){
                foreach (var err in ModelState.Values)
                {
                    foreach (var error in err.Errors)
                    {
                        xb.Append($"{ error.ErrorMessage } { Environment.NewLine }");
                        ModelState.AddModelError(string.Empty, error.ErrorMessage );
                    }
                }
                return View(businessModel);
                // return Content(xb.ToString());
            }
            if(!businessModel.PermitFee1.IsEmpty() && !businessModel.Php1.HasValue){
                ModelState.AddModelError(string.Empty, "Oops!? Permet 2. amount must not empty!");
                return View(businessModel);
            }
            if(!businessModel.PermitFee2.IsEmpty() && !businessModel.Php2.HasValue){
                ModelState.AddModelError(string.Empty, "Oops!? Permet 3. amount must not empty!");
                return View(businessModel);
            }
            if(!businessModel.PermitFee3.IsEmpty() && !businessModel.Php3.HasValue){
                ModelState.AddModelError(string.Empty, "Oops!? Permet 3. amount must not empty!");
                return View(businessModel);
            }
            var api=  new APIBusiness();
            businessModel.ReleasedBy = LoggedUser;
            var result = await api.SavePermit(businessModel);
            if(result.status){
                TempData["Success"] = result.message;
                return RedirectToAction(nameof(NewBusiness));
            }
            TempData["Error"] = result.message;
            return View(businessModel);
            
            // return Content(Newtonsoft.Json.JsonConvert.SerializeObject(businessModel));
        }

        public IActionResult ViewBusiness() => View();

        [HttpPost]
        public async Task<JsonResult> GetBusiness()
        {
            int start = Request.Form["start"].ToString().ValidateNumber(),
                length = Request.Form["length"].ToString().ValidateNumber();

            string search = Request.Form["search[value]"];
            
            var api = new APIBusiness();
            var result = await api.GetBusiness(start, length, search);
            return Json(new{
                data = result.list,
                recordsFiltered = result.count,
                recordsTotal = result.count
            });
        }

        [HttpGet("[controller]/EditBusiness/{key}")]
        public async Task<IActionResult> EditBusiness(string key){
            if(!key.IsValidKey()){
                return NotFound();
            }
            var api = new APIBusiness();
            var row = await api.EditBusiness(key.DecryptString().ValidateNumber());
            return View(row);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> EditBusiness(BusinessModel businessModel)
        {
            var xb = new System.Text.StringBuilder();
            if(!ModelState.IsValid){
                foreach (var err in ModelState.Values)
                {
                    foreach (var error in err.Errors)
                    {
                        xb.Append($"{ error.ErrorMessage } { Environment.NewLine }");
                        ModelState.AddModelError(string.Empty, error.ErrorMessage );
                    }
                }
                return View(businessModel);
                // return Content(xb.ToString());
            }
            if(!businessModel.PermitFee1.IsEmpty() && !businessModel.Php1.HasValue){
                ModelState.AddModelError(string.Empty, "Oops!? Permet 2. amount must not empty!");
                return View(businessModel);
            }
            if(!businessModel.PermitFee2.IsEmpty() && !businessModel.Php2.HasValue){
                ModelState.AddModelError(string.Empty, "Oops!? Permet 3. amount must not empty!");
                return View(businessModel);
            }
            if(!businessModel.PermitFee3.IsEmpty() && !businessModel.Php3.HasValue){
                ModelState.AddModelError(string.Empty, "Oops!? Permet 3. amount must not empty!");
                return View(businessModel);
            }
            var api=  new APIBusiness();
            businessModel.ReleasedBy = nameof(BarangaySystem);
            var result = await api.UpdatePermit(businessModel);
            if(result.status){
                TempData["Success"] = result.message;
                return View();
            }
            TempData["Error"] = result.message;
            return View(businessModel);
            
            // return Content(Newtonsoft.Json.JsonConvert.SerializeObject(businessModel));
        }

        
    }
}

Views/Business/EditBusiness.cshtml
@model BarangaySystem.Models.PermitModels.BusinessModel
@{
    Layout = "~/Views/Shared/_BusinessPermit.cshtml";
}
<section>
    <form asp-action="EditBusiness" asp-controller="Business" method="post">
        <div class="row">
            <div class="col-xs-12">
                <div class="pull-right">
                    <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Update</button>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2><i class="fa fa-file-text"></i> Add Business Request</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <!--content here...-->
                        @if(TempData["Success"] != null){
                            <div class="row">
                                <div class="col-md-12">
                                        <div class="alert alert-success">
                                            @TempData["Success"]
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true">×</span>
                                            </button>
                                        </div>
                                    </div>
                            </div>
                        }
                        @if(TempData["Error"] != null){
                            <div class="row">
                                <div class="col-md-12">
                                        <div class="alert alert-danger">
                                            @TempData["Error"]
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true">×</span>
                                            </button>
                                        </div>
                                    </div>
                            </div>
                        }
                        <div asp-validation-summary="ModelOnly" class="alert alert-danger"></div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Name of Requestor: </label>
                                <input asp-for="Name" class="form-control" placeholder="Enter Name" autofocus>
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="col-md-6">
                                <label>Business Name: </label>
                                <input asp-for="BusinessName" class="form-control" placeholder="Enter BusinessName">
                                <span asp-validation-for="BusinessName" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Business Address: </label>
                                <input asp-for="BusinessAddress" class="form-control" placeholder="Enter Business Address">
                                <span asp-validation-for="BusinessAddress" class="text-danger"></span>
                            </div>
                            <div class="col-md-6">
                                <label>Business Permit Number: </label>
                                <input asp-for="Bbpno" class="form-control" placeholder="Enter Business Permit Number">
                                <span asp-validation-for="Bbpno" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-3">
                                <label>Date Requested: </label>
                                <input id="DateTime" asp-for="DateRequested" class="form-control date-picker" type="text" placeholder="Enter Date Requested">
                                <span asp-validation-for="DateRequested" class="text-danger"></span>
                            </div>
                            <div class="col-md-3">
                                <label>Type Of Request: </label>
                                <select asp-for="TypeOfRequest" class="form-control">
                                    <option>New</option>
                                    <option>Renewal</option>
                                </select>
                                <span asp-validation-for="TypeOfRequest" class="text-danger"></span>
                            </div>
                            <div class="col-md-6">
                                <label>Assessed By: </label>
                                <input asp-for="AssessedBy" class="form-control" placeholder="Enter Assessed By">
                                <span asp-validation-for="AssessedBy" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Payments Total: ₱<a id="total">0.00</a></h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <div class="row">
                            <div class="col-md-6">
                                <label>Permit Fee: </label>
                            </div>
                            <div class="col-md-6">
                                <label>Tax Due: </label>
                            </div>
                        </div>
                        <!-- 1 -->
                        <div class="row">
                            <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
                                <input asp-for="PermitFee" class="form-control has-feedback-left" placeholder="Enter Permit Fee Decription">
                                <span asp-validation-for="PermitFee" class="text-danger"></span>
                                <span class="form-control-feedback left" aria-hidden="true">1. </span>
                            </div>
                            <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
                                <input asp-for="Php" class="fee form-control has-feedback-left"placeholder="Enter Amount">
                                <span asp-validation-for="Php" class="text-danger"></span>
                                <span class="form-control-feedback left" aria-hidden="true">₱</span>
                            </div>
                        </div>
                        <!-- 2 -->
                        <div class="row">
                            <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
                                <input asp-for="PermitFee1" class="form-control has-feedback-left" placeholder="Enter Permit Fee Decription">
                                <span class="form-control-feedback left" aria-hidden="true">2. </span>
                            </div>
                            <div class="col-md-6 col-sm-6 col-xs-12 form-group">
                                <input asp-for="Php1" class="fee form-control has-feedback-left" placeholder="Enter Amount">
                                <span class="form-control-feedback left" aria-hidden="true">₱</span>
                            </div>
                        </div>
                        <!-- 3 -->
                        <div class="row">
                            <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
                                <input asp-for="PermitFee2" class="form-control has-feedback-left" placeholder="Enter Permit Fee Decription">
                                <span class="form-control-feedback left" aria-hidden="true">2. </span>
                            </div>
                            <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
                                <input asp-for="Php2" class="fee form-control has-feedback-left" placeholder="Enter Amount">
                                <span class="form-control-feedback left" aria-hidden="true">₱</span>
                            </div>
                        </div>
                        <!-- 4 -->
                        <div class="row">
                            <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
                                <input asp-for="PermitFee3" class="form-control has-feedback-left" placeholder="Enter Permit Fee Decription">
                                <span class="form-control-feedback left" aria-hidden="true">2. </span>
                            </div>
                            <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
                                <input asp-for="Php3" class="fee form-control has-feedback-left" placeholder="Enter Amount">
                                <span class="form-control-feedback left" aria-hidden="true">₱</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</section>

Views/Business/NewBusiness.cshtml
@model BarangaySystem.Models.PermitModels.BusinessModel
@{
    Layout = "~/Views/Shared/_BusinessPermit.cshtml";
}
<section>
    <form asp-action="NewBusiness" asp-controller="Business" method="post">
        <div class="row">
            <div class="col-xs-12">
                <div class="pull-right">
                    <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Submit</button>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2><i class="fa fa-file-text"></i> Add Business Request</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <!--content here...-->
                        @if(TempData["Success"] != null){
                            <div class="row">
                                <div class="col-md-12">
                                        <div class="alert alert-success">
                                            @TempData["Success"]
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true">×</span>
                                            </button>
                                        </div>
                                    </div>
                            </div>
                        }
                        @if(TempData["Error"] != null){
                            <div class="row">
                                <div class="col-md-12">
                                        <div class="alert alert-danger">
                                            @TempData["Error"]
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true">×</span>
                                            </button>
                                        </div>
                                    </div>
                            </div>
                        }
                        <div asp-validation-summary="ModelOnly" class="alert alert-danger"></div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Name of Requestor: </label>
                                <input asp-for="Name" class="form-control" placeholder="Enter Name" autofocus>
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="col-md-6">
                                <label>Business Name: </label>
                                <input asp-for="BusinessName" class="form-control" placeholder="Enter BusinessName">
                                <span asp-validation-for="BusinessName" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Business Address: </label>
                                <input asp-for="BusinessAddress" class="form-control" placeholder="Enter Business Address">
                                <span asp-validation-for="BusinessAddress" class="text-danger"></span>
                            </div>
                            <div class="col-md-6">
                                <label>Business Permit Number: </label>
                                <input asp-for="Bbpno" class="form-control" placeholder="Enter Business Permit Number">
                                <span asp-validation-for="Bbpno" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-3">
                                <label>Date Requested: </label>
                                <input id="DateTime" asp-for="DateRequested" class="form-control date-picker" type="text" placeholder="Enter Date Requested">
                                <span asp-validation-for="DateRequested" class="text-danger"></span>
                            </div>
                            <div class="col-md-3">
                                <label>Type Of Request: </label>
                                <select asp-for="TypeOfRequest" class="form-control">
                                    <option>New</option>
                                    <option>Renew</option>
                                </select>
                                <span asp-validation-for="TypeOfRequest" class="text-danger"></span>
                            </div>
                            <div class="col-md-6">
                                <label>Assessed By: </label>
                                <input asp-for="AssessedBy" class="form-control" placeholder="Enter Assessed By">
                                <span asp-validation-for="AssessedBy" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Payments Total: ₱<a id="total">0.00</a></h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <div class="row">
                            <div class="col-md-6">
                                <label>Permit Fee: </label>
                            </div>
                            <div class="col-md-6">
                                <label>Tax Due: </label>
                            </div>
                        </div>
                        <!-- 1 -->
                        <div class="row">
                            <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
                                <input asp-for="PermitFee" class="form-control has-feedback-left" placeholder="Enter Permit Fee Decription">
                                <span asp-validation-for="PermitFee" class="text-danger"></span>
                                <span class="form-control-feedback left" aria-hidden="true">1. </span>
                            </div>
                            <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
                                <input asp-for="Php" class="fee form-control has-feedback-left"placeholder="Enter Amount">
                                <span asp-validation-for="Php" class="text-danger"></span>
                                <span class="form-control-feedback left" aria-hidden="true">₱</span>
                            </div>
                        </div>
                        <!-- 2 -->
                        <div class="row">
                            <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
                                <input asp-for="PermitFee1" class="form-control has-feedback-left" placeholder="Enter Permit Fee Decription">
                                <span class="form-control-feedback left" aria-hidden="true">2. </span>
                            </div>
                            <div class="col-md-6 col-sm-6 col-xs-12 form-group">
                                <input asp-for="Php1" class="fee form-control has-feedback-left" placeholder="Enter Amount">
                                <span class="form-control-feedback left" aria-hidden="true">₱</span>
                            </div>
                        </div>
                        <!-- 3 -->
                        <div class="row">
                            <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
                                <input asp-for="PermitFee2" class="form-control has-feedback-left" placeholder="Enter Permit Fee Decription">
                                <span class="form-control-feedback left" aria-hidden="true">2. </span>
                            </div>
                            <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
                                <input asp-for="Php2" class="fee form-control has-feedback-left" placeholder="Enter Amount">
                                <span class="form-control-feedback left" aria-hidden="true">₱</span>
                            </div>
                        </div>
                        <!-- 4 -->
                        <div class="row">
                            <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
                                <input asp-for="PermitFee3" class="form-control has-feedback-left" placeholder="Enter Permit Fee Decription">
                                <span class="form-control-feedback left" aria-hidden="true">2. </span>
                            </div>
                            <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
                                <input asp-for="Php3" class="fee form-control has-feedback-left" placeholder="Enter Amount">
                                <span class="form-control-feedback left" aria-hidden="true">₱</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</section>

Views/Business/ViewBusiness.cshtml
@{
    Layout = "~/Views/Shared/_ViewBusiness.cshtml";
}

<section>
    <div class="row">
        <div class="col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2><i class="fa fa-file-text"></i> Business Permits</h2> <a href="~/Payment/ViewPayment" class="btn btn-sm btn-info" style="float:right;"><i class="fa fa-eye"></i> View Payments</a>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="table-responsive">
                        <table id="tblBusiness" class="table datatable table-bordered">
                            <thead>
                                <tr>
                                    <th>Date</th>
                                    <th>Name</th>
                                    <th>Business</th>
                                    <th>Address</th>
                                    <th>Total Tax</th>
                                    <th>Type</th>
                                    <th>Released By</th>
                                    <th>Action</th>
                                </tr>
                            </thead> 
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>