Controllers/BlotterController.cs
using System;
using System.Linq;
using BarangaySystem.Data;
using BarangaySystem.Models.APIServices;
using BarangaySystem.Models.BlotterModels;
using BarangaySystem.Models.IdentityModels;
using BarangaySystem.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BarangaySystem.Controllers
{
    [Authorize]
    public class BlotterController : Controller
    {
        public readonly UserManager<ApplicationUser> _userManager;

        public BlotterController(UserManager<ApplicationUser> userManager){

            _userManager = userManager;
        }
            
        private string LoggedUser{
            get{
                return _userManager.Users.FirstOrDefault(x => x.UserName == User.Identity.Name).Fullname;
            }
        }
        public IActionResult ViewBlotter() => View();
        public IActionResult NewBlotter() => View();

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult SaveNewBlotter(BlotterModel blotterModel)
        {
            string message = string.Empty;
            if (!ModelState.IsValid)
            {
                foreach (var err in ModelState.Values)
                {
                    foreach (var error in err.Errors)
                    {
                        message = "Oppss.!! Error!";
                        TempData["Error"] = message;
                        ModelState.AddModelError(string.Empty, error.ErrorMessage);
                    }
                }
                return RedirectToAction(nameof(BlotterController.NewBlotter), blotterModel);
            }
            var api = new APIBlotter();
            bool flag = api.Add(blotterModel: blotterModel, addedBy: LoggedUser, message: out message);
            if(!flag)
            {
                ModelState.AddModelError(string.Empty, message);
                return View("NewBlotter", blotterModel);
            }
            message = "Person Data has been Successfully Added";
            TempData["Success"] = message;
            return RedirectToAction(nameof(BlotterController.NewBlotter));
        }

        [HttpGet("[controller]/EditBlotter/{key}")]
        public IActionResult EditBlotter(string key)
        {
            if (!key.IsValidKey())
            {
                return NotFound();
            }
            var api = new APIBlotter();
            string id = key.DecryptString();
            return View(api.GetBlotter(int.Parse(id)));
        }

        public IActionResult ViewDesc(string key)
        {
            if (!key.IsValidKey())
            {
                return NotFound();
            }
            var api = new APIBlotter();
            string id = key.DecryptString();
            return View(api.GetDesc(int.Parse(id)));
        }

        
        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult UpdateBlotter(BlotterModel blotterModel)
        {
            if (!ModelState.IsValid)
            {
                foreach (var err in ModelState.Values)
                {
                    foreach (var error in err.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.ErrorMessage);
                    }
                }
                return View(nameof(EditBlotter), blotterModel);
            }

            if(!blotterModel.Id.ToString().Validate(blotterModel.Key))
            {
                return View(nameof(EditBlotter), blotterModel);
            }

            var api = new APIBlotter();
            string message = string.Empty;
            bool flag = api.Update(blotterModel: blotterModel, addedBy:LoggedUser, message: out message);
            if(!flag)
            {
                ModelState.AddModelError(string.Empty, message);
                return View(nameof(EditBlotter), blotterModel);
            }
            TempData["Success!"] = message;
            return RedirectToAction(nameof(BlotterController.ViewBlotter));
        }


        [HttpPost]
        public JsonResult GetBlotterData(){

            string search = Request.Form["search[value]"];
            int start = int.Parse(Request.Form["start"]),
                pageSize = int.Parse(Request.Form["length"]),
                count = 0;
            var db = new DbBarangayContext();
            var query = db.Blotter;
            count = query.Count();
            var rows = query.OrderByDescending(x => x.Id).Skip(start).Take(pageSize);

            var api = new APIBlotter();
            var result = !search.IsEmpty() ? api.SearchBlotterData(search,start,pageSize, out count) : 
                                             api.GetBlotterData(start,pageSize, out count);
            return Json(new{
                data = result,
                draw = Request.Form["draw"],
                recordsTotal = count,
                recordsFiltered = count,
            });
        }

        [HttpGet]
        public JsonResult Remove(string key)
        {
            var api = new APIBlotter();
            string message = string.Empty;
            var flag = api.Delete(key.DecryptString().ValidateNumber(), addedBy:LoggedUser, message: out message);

            return Json(new{
                status = flag,
                message = message
            });
        }
        
    }
}

Views/Blotter/EditBlotter.cshtml
@model BarangaySystem.Models.BlotterModels.BlotterModel
@{
    //
}
<section>
    <div class="row">
        <div class="col-xs-12">
        <div class="col-md-12">
            <a class="btn btn-primary pull-right action" asp-action="index" asp-controller="Home"><i class="fa fa-arrow-left"></i>Back to Home</a>
        </div>
            <div class="x_panel">
                <div class="x_title">
                    <h2> Edit Records of Complaints</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <!--content here...-->
                @if(TempData["Success"] != null){
                <div class="row">
                    <div class="col-md-12">
                            <div class="alert alert-success">
                                @TempData["Success"]
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">×</span>
                                </button>
                            </div>
                        </div>
                </div>
            }
            @if(TempData["ErrorBrad"] != null){
                <div class="row">
                    <div class="col-md-12">
                            <div class="alert alert-danger">
                                @TempData["ErrorBrad"]
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">×</span>
                                </button>
                            </div>
                        </div>
                </div>
            }<div asp-validation-summary="ModelOnly" class="alert alert-danger"></div>
                    <form asp-action="UpdateBlotter" asp-controller="Blotter" method="post">
                        <input asp-for="Id" type="hidden">
                        <input asp-for="Key" type="hidden">
                        <div class="row">
                            <div class="col-md-6">
                                <label>Name: </label>
                                <input asp-for="Name" class="form-control" placeholder="Enter Fullname" autofocus required>
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="col-md-6">
                                <label>Age: </label>
                                <input asp-for="Age" class="form-control" placeholder="Enter Age" required>
                                <span asp-validation-for="Age" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <label>Address: </label>
                                <input asp-for="Address" class="form-control" placeholder="Enter Address" required>
                                <span asp-validation-for="Address" class="text-danger"></span>
                            </div>
                            <div class="col-md-6">
                                <label>Name Of Respondent: </label>
                                <input asp-for="NameOfRespondent" class="form-control" placeholder="Enter Fullname Of Respondent" required>
                                <span asp-validation-for="NameOfRespondent" class="text-danger"></span>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col-md-6">
                                <label>Respondent Address: </label>
                                <input asp-for="RespondentAddress" class="form-control" placeholder="Enter Respondent Address" required>
                                <span asp-validation-for="RespondentAddress" class="text-danger"></span>
                            </div>
                            <div class="col-md-6">
                                <label>Purpose: </label>
                                <input asp-for="Purpose" class="form-control" placeholder="Enter Respondent Purpose">
                                <span asp-validation-for="Purpose" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <label>BPSO on Duty: </label>
                                <input asp-for="BpsoonDuty" class="form-control" placeholder="Enter BPSO on Duty" required>
                                <span asp-validation-for="BpsoonDuty" class="text-danger"></span>
                            </div>
                            <div class="col-md-6">
                                <label>Respondent Estimated Age: </label>
                                <input asp-for="RespondentAge" class="form-control" placeholder="Enter Respondent Estimated Age">
                                <span asp-validation-for="RespondentAge" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <label>Facts: </label>
                                <textarea asp-for="Facts" class="form-control" placeholder="Enter Facts" required></textarea>
                                <span asp-validation-for="Facts" class="text-danger"></span>
                            </div>
                        </div>
                    <div class="col-md-12" style="padding:10px 0px 10px 0px; text-align:right;">
                        <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-check"></i> Submit</button>
                        <button type="button" class="btn btn-sm btn-danger"><i class="fa fa-close"></i> <a asp-action="ViewBlotter" asp-controller="Blotter" style="color:white;">Cancel</a></button>
                    </div>
                </form>

                </div>
            </div>
        </div>
    </div>
</section>

Views/Blotter/NewBlotter.cshtml
@model BarangaySystem.Models.BlotterModels.BlotterModel
@{
    //
}
<section>
    <div class="row">
        <div class="col-xs-12">
            <div class="col-md-12">
                <a class="btn btn-primary pull-right action" asp-action="index" asp-controller="Home"><i class="fa fa-arrow-left"></i>Back to Home</a>
            </div>
            <div class="x_panel">
                <div class="x_title">
                    <h2>Records of Complaints</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <!--content here...-->
                @if(TempData["Success"] != null){
                <div class="row">
                    <div class="col-md-12">
                            <div class="alert alert-success">
                                @TempData["Success"]
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">×</span>
                                </button>
                            </div>
                        </div>
                </div>
            }
            @if(TempData["Error"] != null){
                <div class="row">
                    <div class="col-md-12">
                            <div class="alert alert-danger">
                                @TempData["Error"]
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">×</span>
                                </button>
                            </div>
                        </div>
                </div>
            }
                    <div asp-validation-summary="ModelOnly" class="alert alert-danger"></div>
                    <form asp-action="SaveNewBlotter" asp-controller="Blotter" method="post">
                        <div class="row">
                            <div class="col-md-6">
                                <label>Complainant Name: </label>
                                <input asp-for="Name" class="form-control" placeholder="Enter Fullname" autofocus required>
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="col-md-6">
                                <label>Complainant Age: </label>
                                <input asp-for="Age" class="form-control" placeholder="Enter Age" required>
                                <span asp-validation-for="Age" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <label>Complainant Address: </label>
                                <input asp-for="Address" class="form-control" placeholder="Enter Address" required>
                                <span asp-validation-for="Address" class="text-danger"></span>
                            </div>
                            <div class="col-md-6">
                                <label>Name Of Respondent: </label>
                                <input asp-for="NameOfRespondent" class="form-control" placeholder="Enter Fullname Of Respondent" required>
                                <span asp-validation-for="NameOfRespondent" class="text-danger"></span>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col-md-6">
                                <label>Respondent Address: </label>
                                <input asp-for="RespondentAddress" class="form-control" placeholder="Enter Respondent Address" required>
                                <span asp-validation-for="RespondentAddress" class="text-danger"></span>
                            </div>
                            <div class="col-md-6">
                                <label>Purpose: </label>
                                <input asp-for="Purpose" class="form-control" placeholder="Enter Respondent Purpose">
                                <span asp-validation-for="Purpose" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <label>BPSO on Duty: </label>
                                <input asp-for="BpsoonDuty" class="form-control" placeholder="Enter BPSO on Duty" required>
                                <span asp-validation-for="BpsoonDuty" class="text-danger"></span>
                            </div>
                            <div class="col-md-6">
                                <label>Respondent Estimated Age: </label>
                                <input asp-for="RespondentAge" class="form-control" placeholder="Enter Respondent Estimated Age">
                                <span asp-validation-for="RespondentAge" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <label>Facts: </label>
                                <textarea asp-for="Facts" class="form-control" placeholder="Enter Facts" required></textarea>
                                <span asp-validation-for="Facts" class="text-danger"></span>
                            </div>
                        </div>

                    <div class="col-md-12" style="padding:10px 0px 10px 0px; text-align:right;">
                        <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-check"></i> Submit</button>
                        <button type="button" class="btn btn-sm btn-danger"><i class="fa fa-close"></i> <a asp-action="ViewBlotter" asp-controller="Blotter" style="color:white;">Cancel</a></button>
                    </div>
                </form>

                </div>
            </div>
        </div>
    </div>
</section>

Views/Blotter/ViewBlotter.cshtml
@{
    Layout = "~/Views/Shared/_ViewBlotter.cshtml";
}

<section>
    <div class="row">
        <div class="col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Blotter Records</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    @if(TempData["Success!"] != null){
                <div class="row">
                    <div class="col-md-12">
                            <div class="alert alert-success">
                                @TempData["Success!"]
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">×</span>
                                </button>
                            </div>
                        </div>
                </div>
            }
                    <!--content here...-->      
                    <table id="tblBlotter" class="table datatable table-bordered">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Age</th>
                                <th>Address</th>
                                <th>Name Of Respondent</th>
                                <th>Respondent Address</th>
                                <th>Respondent Age</th>
                                <th>Purpose</th>
                                <th>BPSO on Duty</th>
                                <th>Facts</th>
                                <th>Date</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</section>

Views/Blotter/ViewDesc.cshtml
@model BarangaySystem.Models.BlotterModels.BlotterModel
@{
    //
}
<section>
    <div class="row">
        <div class="col-xs-12">
        <div class="col-md-12">
            <a class="btn btn-sm btn-info pull-right action" asp-action="ViewBlotter" asp-controller="Blotter"><i class="fa fa-arrow-left"></i> Back</a>
        </div>
            <div class="x_panel">
                <div class="x_title">
                    <h2> Complainant Facts / Description <b>@Model.Name</b></h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <!--content here...-->
                        <input asp-for="Id" type="hidden">
                        <input asp-for="Key" type="hidden">
                        <div class="row">
                            <div class="col-md-6">
                                <pre class="fact"> @Model.Facts</pre>
                            </div>
                        </div>

                </div>
            </div>
        </div>
    </div>
</section>